# Generated by Django 3.1.7 on 2021-02-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Image',
            new_name='image',
        ),
    ]
